/**
 * Regenerate src/lib/vault-abi.ts from the contract in this repository.
 *
 *   npm run abi
 *
 * Preflight is the command that gates sending money to a vault, and it needs
 * the vault's ABI to ask the vault anything. It used to get that by compiling
 * the contract, which is the right source but the wrong dependency: solc is a
 * devDependency and `contracts/` is not in the keeper image, so the one check
 * that matters before funding could only run from a full development checkout.
 *
 * So the ABI is generated here and committed. The guarantee is unchanged,
 * because it is still derived from this repository's source rather than
 * hand-written, and test/abi.test.mjs recompiles the contract and fails if the
 * committed file has drifted. A stale ABI is a broken build, not a surprise at
 * the moment of funding.
 *
 * Run this after any change to contracts/ResidentVault.sol and commit the
 * result alongside it.
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { compile } from "../test/harness.mjs";

export const ABI_PATH = join(
  dirname(dirname(fileURLToPath(import.meta.url))),
  "src/lib/vault-abi.ts",
);

/**
 * The file's contents for a given ABI.
 *
 * Exported so the test can build the expected text and compare, rather than
 * re-deriving the formatting and drifting from it.
 */
export function render(abi) {
  return (
    "// Generated by scripts/abi.mjs from contracts/ResidentVault.sol.\n" +
    "// Do not edit. Run `npm run abi` and commit the result.\n" +
    "//\n" +
    "// Committed rather than compiled at startup so that preflight — the check\n" +
    "// that gates funding — runs anywhere the keeper runs, including inside the\n" +
    "// container, which carries neither solc nor the contract source.\n" +
    "// test/abi.test.mjs recompiles and fails if this has drifted.\n\n" +
    `export const VAULT_ABI = ${JSON.stringify(abi, null, 2)} as const;\n`
  );
}

export function vaultAbi() {
  const { artifacts } = compile();
  return artifacts.ResidentVault.abi;
}

// Only when run directly. Importing this from the test must not write a file:
// a generator that regenerates on import can never fail its own drift check.
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(ABI_PATH, render(vaultAbi()));
  console.log(`wrote ${ABI_PATH}`);
}
